import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Providers from './providers';
import BackButton from '@/components/BackButton';
import pokeballIcon from '@/assets/pokeball.png';
import Image from 'next/image';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import ToastProvider from '@/components/ToastContainer';
import Navigation from '@/components/Navigation';

const poppins = Poppins({
  weight: ['600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Pokemon App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Providers>
          <ToastProvider>
            <div className="flex flex-col w-full h-[100vh]">
              <header className="sticky top-0 z-50 w-full flex flex-row justify-center items-center p-4 text-black bg-light-header dark:bg-dark-header">
                <BackButton />
                <span className="animate-bounce">
                  <Image
                    src={pokeballIcon}
                    width={48}
                    height={48}
                    alt="pokeball-icon"
                  />
                </span>
              </header>
              <main className="relative h-full overflow-auto bg-light-main dark:bg-dark-main text-black dark:text-white">
                {children}
              </main>
              <Navigation />
            </div>
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
